version: '3.8'
services:
  db:
    image: postgres:15
    container_name: videoedu_db
    environment:
      POSTGRES_USER: zulip_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: zulip_events
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Монтируем init.sql в контейнер
    ports:
      - "5434:5432"

volumes:
  db_data:
